insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.title.course.add'),
    (nextval('less_planning.localization_id_seq'), 'ui.title.course.edit'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.course.add'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.course.edit');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.course.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Добавление курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.course.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Добавление курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.course.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'LP: Add course'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Добавление курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Добавление курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Add course'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.course.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Редактирование курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.course.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Редактирование курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.course.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'LP: Edit course'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Edit course');