insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.title.user.list'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.user.list'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.user.add'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.role'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.roles'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.last_auth_ip'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.last_auth_date'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.users');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.user.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Список пользователей'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.user.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Список пользователей'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.user.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'LP: Users'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.user.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Список пользователей'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.user.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Список пользователей'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.user.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Users'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.user.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Регистрация пользователя'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.user.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Регистрация пользователя'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.user.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'User registration'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.role'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Роль'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.role'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Роль'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.role'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Role'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.roles'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Роли'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.roles'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Роли'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.roles'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Roles'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.last_auth_ip'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Последний IP авторизации'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.last_auth_ip'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Последний IP авторизации'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.last_auth_ip'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Last auth IP'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.last_auth_date'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Последняя дата авторизации'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.last_auth_date'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Последняя дата авторизации'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.last_auth_date'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Last auth date'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.users'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Пользователи'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.users'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Пользователи'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.users'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Users');