insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.button.add'),
    (nextval('less_planning.localization_id_seq'), 'ui.title.course.list'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.course.list'),
    (nextval('less_planning.localization_id_seq'), 'ui.button.edit');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Добавить'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Добавить'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Add'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.course.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Список курсов'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.course.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Список курсов'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.course.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'LP: Courses'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Список курсов'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Список курсов'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Courses'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактировать'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактировать'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Edit');