insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.title.child.list'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.child.add'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.child.edit'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.child.name'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.child.parent'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.phone');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.child.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Дети'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.child.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Дети'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.child.list'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'LP: Children'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Добавление ребёнка'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Добавление ребёнка'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.add'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Add child'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование ребёнка'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование ребёнка'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Edit child'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Имя ребёнка'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Имя ребёнка'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Child name'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.parent'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Имя родителя'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.parent'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Имя родителя'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.parent'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Parent name'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.phone'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Номер телефона'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.phone'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Номер телефона'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.phone'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Phone number');