insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.header.password.change'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.old_password'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.new_password');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.old_password'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Старый пароль'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.old_password'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Старый пароль'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.old_password'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Old password'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.password.change'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Изменение пароля'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.password.change'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Изменение пароля'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.password.change'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Password change'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.new_password'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Новый пароль'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.new_password'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Новый пароль'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.new_password'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'New password');