insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.error.404.title'),
    (nextval('less_planning.localization_id_seq'), 'ui.error.404.header'),
    (nextval('less_planning.localization_id_seq'), 'ui.error.404.text'),
    (nextval('less_planning.localization_id_seq'), 'ui.button.home');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.error.404.title'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Страница не найдена'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.error.404.title'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Страница не найдена'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.error.404.title'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Page not found'),

   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.error.404.header'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Что-то пошло не так'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.error.404.header'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Что-то пошло не так'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.error.404.header'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Something went wrong'),

   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.error.404.text'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Запрашиваемая Вами страница не найдена, возможно она была удалена, либо перемещена'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.error.404.text'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Запрашиваемая Вами страница не найдена, возможно она была удалена, либо перемещена'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.error.404.text'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'The page you requested was not found, it may have been deleted or moved'),

   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.home'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Домой'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.home'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Домой'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.home'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Home');