insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.text.successfully_saved'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.first_name'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.last_name'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.profile.change'),
    (nextval('less_planning.localization_id_seq'), 'ui.title.scheduling.index'),
    (nextval('less_planning.localization_id_seq'), 'ui.title.profile.change');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.successfully_saved'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Успешно сохранено'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.successfully_saved'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Успешно сохранено'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.successfully_saved'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Successfully saved'),

   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.first_name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Имя'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.first_name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Имя'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.first_name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'First name'),

   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.last_name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Фамилия'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.last_name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Фамилия'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.last_name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Last name'),

   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.profile.change'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Обновление профиля'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.profile.change'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Обновление профиля'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.profile.change'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Profile change'),

   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.profile.change'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Обновление профиля'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.profile.change'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Обновление профиля'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.profile.change'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'LP: Profile change'),

   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.scheduling.index'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Расписание'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.scheduling.index'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Расписание'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.scheduling.index'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'LP: Scheduling');