insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.title.lesson.edit'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.lesson.edit'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.date_start'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.date_end');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.lesson.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Редактирование занятия'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.lesson.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Редактирование занятия'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.lesson.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'LP: Lesson edit'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.lesson.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование занятия'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.lesson.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование занятия'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.lesson.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Lesson edit'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.date_start'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Дата начала'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.date_start'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Дата начала'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.date_start'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Start date'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.date_end'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Дата окончания'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.date_end'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Дата окончания'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.date_end'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'End date');