insert into less_planning.locale (id, country_iso3, language_iso3) values
    (nextval('less_planning.locale_id_seq'), null, null),
    (nextval('less_planning.locale_id_seq'), null, 'rus'),
    (nextval('less_planning.locale_id_seq'), null, 'eng');

insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.title.authorization'),

    (nextval('less_planning.localization_id_seq'), 'ui.header.authorization'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.login'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.password'),
    (nextval('less_planning.localization_id_seq'), 'ui.button.sing_in'),
    (nextval('less_planning.localization_id_seq'), 'ui.button.log_out'),

    (nextval('less_planning.localization_id_seq'), 'ui.header.courses'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.scheduling'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.children'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.course.name'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.course_edit'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.lesson_edit'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.edit'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.remove'),

    (nextval('less_planning.localization_id_seq'), 'ui.text.lesson'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.n_notes'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.children'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.scheduling_time'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.lesson_time'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.remove_lesson'),

    (nextval('less_planning.localization_id_seq'), 'ui.button.save'),
    (nextval('less_planning.localization_id_seq'), 'ui.button.create'),
    (nextval('less_planning.localization_id_seq'), 'ui.button.yes'),
    (nextval('less_planning.localization_id_seq'), 'ui.button.no');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.authorization'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Авторизация'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.authorization'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'ПУ: Авторизация'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.title.authorization'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'LP: Authorization'),

     ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.authorization'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Авторизация'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.authorization'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Авторизация'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.authorization'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Authorization'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.login'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Логин'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.login'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Логин'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.login'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Login'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.password'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Пароль'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.password'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Пароль'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.password'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Password'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.sing_in'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Войти'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.sing_in'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Войти'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.sing_in'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Sing In'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.log_out'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Выйти'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.log_out'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Выйти'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.log_out'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Log Out'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.courses'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Курсы'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.courses'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Курсы'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.courses'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Courses'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.scheduling'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Расписание'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.scheduling'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Расписание'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.scheduling'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Scheduling'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.children'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Дети'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.children'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Дети'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.children'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Children'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Название курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Название курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course.name'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Course name'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course_edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course_edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование курса'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.course_edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Course edit'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.lesson_edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование занятия'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.lesson_edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование занятия'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.lesson_edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Lesson edit'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Редактирование'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.edit'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Edit'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.remove'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Удаление'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.remove'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Удаление'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.remove'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Remove');

insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.lesson'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Занятие'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.lesson'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Занятие'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.lesson'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Lesson'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.n_notes'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    '%d записей'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.n_notes'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    '%d записей'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.n_notes'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    '%d notes'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.children'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Дети'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.children'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Дети'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.children'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Children'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.scheduling_time'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Дата записи'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.scheduling_time'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Дата записи'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.scheduling_time'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Scheduling time'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.lesson_time'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Время занятия'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.lesson_time'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Время занятия'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.lesson_time'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Lesson time'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.remove_lesson'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Удалить занятие'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.remove_lesson'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Удалить занятие'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.remove_lesson'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Remove lesson'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.save'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Сохранить'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.save'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Сохранить'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.save'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Save'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.create'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Создать'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.create'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Создать'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.create'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Create'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.yes'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Да'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.yes'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Да'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.yes'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Yes'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.no'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Нет'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.no'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Нет'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.no'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'No');