insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.text.error.user_not_found'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.error.passwords_mismatch'),
    (nextval('less_planning.localization_id_seq'), 'ui.text.error.already_exists');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.error.user_not_found'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Пользователь не найден'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.error.user_not_found'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Пользователь не найден'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.error.user_not_found'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'User not found'),

   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.error.passwords_mismatch'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Пароль не совпадает'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.error.passwords_mismatch'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Пароль не совпадает'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.error.passwords_mismatch'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Password mismatch'),

   ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.error.already_exists'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Уже существует'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.error.already_exists'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Уже существует'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.text.error.already_exists'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Already exists');