insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'ui.header.child.courses_scheduling'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.day_of_week'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.time_start'),
    (nextval('less_planning.localization_id_seq'), 'ui.header.time_end'),
    (nextval('less_planning.localization_id_seq'), 'ui.button.remove');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.courses_scheduling'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Запись на курсы'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.courses_scheduling'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Запись на курсы'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.child.courses_scheduling'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Course scheduling'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.day_of_week'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'День недели'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.day_of_week'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'День недели'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.day_of_week'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Day of week'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.time_start'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Время начала'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.time_start'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Время начала'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.time_start'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Time start'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.time_end'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Время окончания'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.time_end'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Время окончания'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.header.time_end'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Time end'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.remove'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Удалить'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.remove'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Удалить'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'ui.button.remove'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Remove');