insert into less_planning.localization (id, code) values
    (nextval('less_planning.localization_id_seq'), 'api.constraint.empty'),
    (nextval('less_planning.localization_id_seq'), 'api.constraint.invalid'),
    (nextval('less_planning.localization_id_seq'), 'api.constraint.short');


insert into less_planning.translation (locale_id, localization_id, editor_id, update_date_time, translation) values
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'api.constraint.empty'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Не может быть пустым'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'api.constraint.empty'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Не может быть пустым'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'api.constraint.empty'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Can''t be empty'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'api.constraint.invalid'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Недопустимое значение'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'api.constraint.invalid'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Недопустимое значение'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'api.constraint.invalid'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Invalid value'),

    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 is null),
    (select loc.id from less_planning.localization loc where loc.code = 'api.constraint.short'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Слишком мало символов'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'rus'),
    (select loc.id from less_planning.localization loc where loc.code = 'api.constraint.short'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Слишком мало символов'),
    ((select loc.id from less_planning.locale loc where loc.country_iso3 is null and loc.language_iso3 = 'eng'),
    (select loc.id from less_planning.localization loc where loc.code = 'api.constraint.short'),
    (select u.id from less_planning.user u where u.login = 'admin'),
    now(),
    'Too little characters');